# Supabase project configuration

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"

[auth.email]
enable_confirmations = false

[project]

[functions.send-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-email/deno.json"
entrypoint = "./functions/send-email/index.ts"