-- SKIPPED: This migration will be replaced by 20260421120000_rls_modulo_scope_curso.sql
-- SKIP: -- which removes the dependency on get_my_highest_role() function

-- Endurece SELECT en modulo: reemplaza lectura abierta por lectura por rol de gestion o estudiante inscrito.
-- DROP POLICY IF EXISTS "Lectura autenticada" ON public.modulo;
-- DROP POLICY IF EXISTS "Lectura modulo por gestion o inscripcion" ON public.modulo;
-- CREATE POLICY "Lectura modulo por gestion o inscripcion"
--   ON public.modulo FOR SELECT
--   TO authenticated
--   USING (
-- SKIP: --     public.get_my_highest_role() = ANY (
--       ARRAY['Super Administrador'::text, 'Administrador de Iglesia'::text, 'Líder'::text]
--     )
--     OR public.can_read_modulo_as_student(id_modulo)
--   );
